apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
  namespace: client
type: Opaque
data:
  GOOGLE_CLIENT_SECRET:
    {
      {
        required "Please provide a value for the google client secret" .Values.client.secrets.googleClientSecret | b64enc,
      },
    }
  GOOGLE_CLIENT_ID:
    {
      {
        required "Please provide a value for the google client id" .Values.client.secrets.googleClientId | b64enc,
      },
    }
