apiVersion: v1
kind: Service
metadata:
  name: cee-intrepreter-service
  namespace: cee-intrepreter
spec:
  type: ClusterIP
  selector:
    app: cee-intrepreter
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cee-intrepreter
  name: cee-intrepreter
  namespace: cee-intrepreter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cee-intrepreter
  template:
    metadata:
      labels:
        app: cee-intrepreter
    spec:
      containers:
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          resources:
            limits:
              memory: "200Mi"
              cpu: 0.3
            requests:
              memory: "200Mi"
              cpu: 0.3
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/
            - name: code
              mountPath: /app/code
        - name: cee-intrepreter
          image: chan1992241/cee-interpreter:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/
            - name: code
              mountPath: /app/code
          resources:
            limits:
              memory: "50Mi"
              cpu: 0.1
            requests:
              memory: "50Mi"
              cpu: 0.1
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: cee-intrepreter-configmap
            - secretRef:
                name: cee-intrepreter-secrets
      volumes:
        - name: dockersock
          emptyDir: {}
        - name: code
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cee-intrepreter-configmap
  namespace: cee-intrepreter
data:
  REDIS_SENTINELS: sentinel.redis.svc.cluster.local
  SUBMISSION_QUEUE: submission-queue.submission-queue.svc.cluster.local
  CEE_INTERPRETER_QUEUE_NAME: cee-intrepreter-queue
  ENVIRONMENT: development
