---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  selector:
    app: router-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name:
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: router-app
  name: router-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-app
  template:
    metadata:
      labels:
        app: router-app
    spec:
      containers:
        - name: router-app
          image: chan1992241/router:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
