apiVersion: v1
kind: Secret
metadata:
  name: router-secrets
  namespace: router
type: Opaque
data:
  REDIS_PASSWORD: YS12ZXJ5LWNvbXBsZXgtcGFzc3dvcmQtaGVyZQo=
  REDIS_MASTER_NAME: bXltYXN0ZXIK
  RABBMITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
