---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cee
  name: cee
  namespace: cee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cee
  template:
    metadata:
      labels:
        app: cee
    spec:
      containers:
        - name: cee
          image: chan1992241/cee:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1000Mi"
              cpu: 1
            requests:
              memory: "200Mi"
              cpu: 0.5
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: cee-configmap
            - secretRef:
                name: cee-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cee-configmap
  namespace: cee
data:
  REDIS_SENTINELS: sentinel.redis.svc.cluster.local
  SUBMISSION_QUEUE: amqp://submission-queue.submission-queue.svc.cluster.local:5672/
  REDIS_HOST: redis.redis.svc.cluster.local
  CEE_INTERPRETER_QUEUE_NAME: cee-intrepreter-queue
  # SUPPORTED_LANGUAGES: python@python:alpine3.16@python-code.py@.py,nodejs@node:lts-alpine3.17@node-code.js,c@frolvlad/alpine-gxx,cpp:frolvlad/alpine-gxx,rust:frolvlad/alpine-rust
  SUPPORTED_LANGUAGES: python@python:alpine3.16@python-code.py@.py
  ENVIRONMENT: development
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cee-scaledobject
  namespace: cee
spec:
  scaleTargetRef:
    name: cee
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        vhostName: /
        queueName: cee-intrepreter-queue
        mode: QueueLength
        value: "1"
      authenticationRef:
        name: cee-trigger-auth-rabbitmq-conn
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: cee-trigger-auth-rabbitmq-conn
  namespace: cee
spec:
  secretTargetRef:
    - parameter: host
      name: cee-secrets
      key: RABBITMQ_HOST
