apiVersion: v1
kind: Secret
metadata:
  name: cee-secrets
  namespace: cee
type: Opaque
data:
  REDIS_PASSWORD: YS12ZXJ5LWNvbXBsZXgtcGFzc3dvcmQtaGVyZQo=
  REDIS_MASTER_NAME: bXltYXN0ZXIK
  SUBMISSION_QUEUE: YW1xcDovL3N1Ym1pc3Npb24tcXVldWUuc3VibWlzc2lvbi1xdWV1ZS5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyLw==
  RABBMITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  RABBITMQ_HOST: YW1xcDovL2d1ZXN0Omd1ZXN0QHN1Ym1pc3Npb24tcXVldWUuc3VibWlzc2lvbi1xdWV1ZS5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyLw==
