apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cee-dind
  name: cee-dind
  namespace: cee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cee-dind
  template:
    metadata:
      labels:
        app: cee-dind
    spec:
      containers:
        - name: cee-dind
          image: docker:dind
          securityContext:
            privileged: true
          resources:
            limits:
              memory: "500Mi"
              cpu: 1
            requests:
              memory: "400Mi"
              cpu: 0.7
          volumeMounts:
            - mountPath: /var/run/
              name: cee-dind-volume
      volumes:
        - name: cee-dind-volume
          persistentVolumeClaim:
            claimName: cee-dind-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cee-dind-pvc
  namespace: cee
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Mi
  storageClassName: standard
---
# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cee-dind
  namespace: cee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cee-dind
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
---

