apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cee-compiler
  name: cee-compiler
  namespace: cee-compiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cee-compiler
  template:
    metadata:
      labels:
        app: cee-compiler
    spec:
      containers:
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          resources:
            limits:
              memory: "400Mi"
              cpu: 0.7
            requests:
              memory: "400Mi"
              cpu: 0.7
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/
            - name: code
              mountPath: /app/code
        - name: cee-compiler
          image: chan1992241/cee-compiler:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: 0.1
            requests:
              memory: "100Mi"
              cpu: 0.1
          envFrom:
            - configMapRef:
                name: cee-compiler-configmap
            - secretRef:
                name: cee-compiler-secrets
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/
            - name: code
              mountPath: /app/code
      volumes:
        - name: dockersock
          emptyDir: {}
        - name: code
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cee-compiler-configmap
  namespace: cee-compiler
data:
  REDIS_SENTINELS: sentinel.redis.svc.cluster.local
  SUBMISSION_QUEUE: submission-queue.submission-queue.svc.cluster.local
  CEE_COMPILER_QUEUE_NAME: cee-compiler-queue
  ENVIRONMENT: development
