name: 2. Project Initialization

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - staging
      project:
        type: choice
        description: Project
        options:
        - algorint

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  SERVER_CRT: ${{ secrets.SERVER_CRT }}
  SERVER_KEY: ${{ secrets.SERVER_KEY }}


jobs:
  project:
    name: 'Cluster Initialization'
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: 'Setup NodeJS'
      uses: actions/setup-node@v4
      
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4.0.0
      with:
        version: latest

    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Configure Kube-Config
      run: |
        aws eks --region ap-southeast-1 update-kubeconfig --name eks-cluster
        kubectl version

    - name: Deploy Application Database
      working-directory: ${{ github.workspace }}/application_database/kubernetes
      run: |
        kubectl apply -f mongo-aws.yml

    - name: Deploy Submission Queue
      working-directory: ${{ github.workspace }}/submission_queue/kubernetes
      run: |
        kubectl apply -f submission-queue-aws.yaml

    - name: Deploy Submission Database
      working-directory: ${{ github.workspace }}/submission_database/kubernetes
      run: |
        kubectl apply -f redis-aws.yml
    
    - name: Deploy Router
      working-directory: ${{ github.workspace }}/router/kubernetes/deployment/
      run: |
        kubectl apply -f router-aws.yml
    
    - name: Deploy CEE
      working-directory: ${{ github.workspace }}/cee/kubernetes/deployment
      run: |
        kubectl apply --server-side -f keda-2.11.0.yaml
        kubectl apply -f cee-aws.yml

    - name: Deploy Judge
      working-directory: ${{ github.workspace }}/judge/kubernetes/deployment
      run: |
        kubectl apply -f judge-aws.yml
        
    - name: Deploy Client
      working-directory: ${{ github.workspace }}/client/kubernetes/deployment
      run: |
        sed -i 's/<GOOGLE_CLIENT_SECRET>/${{ env.GOOGLE_CLIENT_SECRET }}/g' client-aws.yaml
        sed -i 's/<GOOGLE_CLIENT_ID>/${{ env.GOOGLE_CLIENT_ID }}/g' client-aws.yaml
        sed -i 's/<SERVER_CRT>/${{ env.SERVER_CRT }}/g' client-aws.yaml
        sed -i 's/<SERVER_KEY>/${{ env.SERVER_KEY }}/g' client-aws.yaml
        kubectl apply -f client-aws.yaml
    
    - name: Get Client Load Balancer
      run: |
        kubectl get svc -n client
